### PR TITLE
docs: Add docs for publishing API and a template script.

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: RW-831

This is a new page for the Publishing (or Post) API - as reviewed on https://unitednations.sharepoint.com/:w:/r/sites/OCHAIMB/Digital%20Services%20Section/06_Projects/ReliefWeb/ReliefWeb%20API/ReliefWeb%20POST%20API%20-%20starting%202024/Publishing%20API%20page%20for%20apidoc.docx?d=wddd9a576e5df4e1f85cb531e22e8fc38&csf=1&web=1&e=xKLclO 

(which is heavily based on: https://unitednations.sharepoint.com/:w:/r/sites/OCHAIMB/Digital%20Services%20Section/06_Projects/ReliefWeb/ReliefWeb%20API/ReliefWeb%20POST%20API%20-%20starting%202024/ReliefWeb%20POST%20API%20-%20Documentation%20-%2018%20June%202024.docx?d=w82a6f851b3954f3aafaf5395f7ce5f95&csf=1&web=1&e=ZPFowp ).

It also includes a template script to create an example request for a report. The API key will be presented separately, but at the same time we should have enough information (provider id, trusted domains, source_id etc) to fill in the basics for a successful PUT request. 

It could be more generic, but it was a useful exercise to base it on a real report.

If the template script seems useful, I can do the same for Jobs and Training.

### CODE REVIEW

**Review by orakili — APPROVED** [review]
Approving but the naming is still being discussed and the API has not yet been released so marking as blocked.

**Comment by lazysoundsystem** [comment]
Added a notice that the api is still in testing, 
image

and it's not yet linked to in the Menu, so not very discoverable.

@orakili do you have an opinion on renaming it the Publishing API? I see the module is `reliefweb_post_api`, which we can rename if we think it's worth it, but might there be any other side effects? If not, I think we can publish this already and consider adding the page to the menu.

**Review by orakili — CHANGES_REQUESTED** [review]
I think that all the API URLS used for the publishing API (scripts, publishing.html etc.) should use `https://test.api-reliefweb-int.ahconu.org/v2` instead of `https://api.reliefweb.int/v1` to avoid confusion. Mixing v1 and v2 in the doc or script is disorienting.

Also using `https://reliefweb.int/job/4114777/team-lead-health-activity` for the job URL in the script is confusing. It should be the URL of the job on the "International Rescue Committee" site. Same thing for the training script.

In the report script, the source is FEWS but the report URL is from unocha.org, that also needs to be changed to the URL of the document on FEWS.

**Comment by lazysoundsystem** [comment]
Thanks @orakili I've made them a bit more consistent and made some changes after testing the job template.

I'm going to merge this now so we can link to the publishing page - I think we don't need to make the templates public, but can adapt them for each new provider based on their own content.

**Pull request merged**
